# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_auto_20190304_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctacte',
            name='factura',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='ctacte',
            name='sociedad',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
