# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_auto_20190304_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='tipoUsr',
            field=models.CharField(choices=[('A', 'Administrador'), ('I', 'Inquilino')], default='A', max_length=15),
        ),
    ]
