# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_auto_20190304_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='nro_inquilino',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ctacte',
            name='saldo',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
