# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0007_ctacte_nro_inquilino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.BinaryField(),
        ),
    ]
