# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0008_auto_20190329_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctacte',
            name='inquilino',
        ),
    ]
