# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='inquilino',
            field=models.IntegerField(auto_created=True),
        ),
    ]
