# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 01:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_auto_20190304_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='inquilino',
        ),
        migrations.AlterField(
            model_name='ctacte',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
